### ISSUE TITLE
Onboard as a TechFolio Developer

### ISSUE THREAD

**Issue by philipmjohnson** [techfolios/techfoliodesigner#16]
Here are the steps required to get familiar with TechFolio Designer as a developer.

### 1. Install a binary release and learn the system from the User perspective.

First, get some experience with TechFolio Designer as a user.  Follow the instructions in the [TechFolio Designer User Guide](http://techfolios.github.io/designer.html) to download and install a release. 

Follow the instructions to download your portfolio. Make a simple change, publish the results, and make sure they appear in your online portfolio.

### 2. Set up your development environment.

Follow the instructions in the [TechFolio Designer Developer Guide](https://techfolios.github.io/techfoliodesigner/) to set up your development environment. Make sure you can run the system locally. 

Set up IntelliJ IDEA with a new project pointing to the source code for TechFolio Designer. Make a small change to a page, and check to see that your local run of the system reflects that change.

### 3. Write and publish an essay about your experiences onboarding as a TechFolio Designer developer.

Now that you have worked through the basics, it's time to use TechFolio Designer for real.  Create a new essay about your experiences onboarding as a TechFolio Designer developer. Some of the issues you might want to cover in your essay include:

  * Why are you interested in TechFolio Designer development?
  * What problems have you run into while creating your professional portfolio in the past that you hope will be solved for other students in the future by using TechFolio Designer?
  * What problems did you encounter while using a binary release of TechFolio Designer?  How could these problems be solved?
  * What problems did you encounter while setting up your development environment? 
  * What parts of TechFolio Designer are you interested in improving?

When you are finished with your essay, publish it and add the URL as a comment to this issue so that everyone can see it.

### 4. Join the techfolio Slack workspace, and post your essay.

Now, join the TechFolios Slack Workspace using [https://join.slack.com/t/techfolios/signup](https://join.slack.com/t/techfolios/signup). (You need to have a hawaii.edu email address). 

Once you're in, please post the URL to your essay to the onboarding channel.

**Comment by blaine-wataru** [comment]
https://blaine-wataru.github.io/essays/techfolios.html

**Comment by adi-kumar** [comment]
https://adi-kumar.github.io/essays/on-boarding.html

**Comment by mhsakuda** [comment]
https://mhsakuda.github.io/essays/2018-08-23.html

**Comment by zhime** [comment]
https://zhime.github.io/essays/techfolioux.html

**Comment by rcammack** [comment]
https://rcammack.github.io/essays/techFolioDesigner.html

**Comment by saehyuns** [comment]
https://saehyuns.github.io/essays/TechFoliosOnboarding.html

**Comment by kiankoba** [comment]
https://kiankoba.github.io/essays/techfoliosonboarding.html
