### ISSUE TITLE
Fix git cloning issues on Windows

### ISSUE THREAD

**Issue by philipmjohnson** [techfolios/techfoliodesigner#20]
Please do work for this task in a branch called issue-20.

According to [Adi](https://adi-kumar.github.io/essays/on-boarding.html), "I tried to install the binary release (on Windows) but ran into various errors related to git when cloning the github.io repository within the GUI. "

Please replicate these problems, specify them as a comment to this issue, and fix.

Requires a developer with access to a Windows machine.

**Comment by philipmjohnson** [comment]
@klauritz sent me the following DM:

Hi professor. I believe I found the solution to the issue #20. It seems it doesn't work on Git version 2.11, but as soon as I updated my Git, Techfolio was able to clone my repo successfully. Two my my Windows machines failed to clone on Git version 2.11, but both worked just fine on version 2.18.

**Comment by klauritz** [comment]
Adi confirmed with me that it worked when he upgraded to the latest Git.

**Comment by philipmjohnson** [comment]
I've updated the documentation to reflect this constraint.
