### ISSUE TITLE
Onboard as a TechFolio Developer, Part 2

### ISSUE THREAD

**Issue by philipmjohnson** [techfolios/techfoliodesigner#22]
Please do work for this task in a branch off master called issue-22-NAME, where NAME is replaced by your first name. For example, "issue-22-philip", "issue-22-riley", etc. Each developer should work in their own branch to complete this task.  Feel free to work with each other, but do not copy each others code. You must type in all the code yourself. You will not merge your branch into master; this task is simply to help you get up to speed making modifications to the TechFolio Designer code base.

## Review TechFolio Designer technologies

Begin by reviewing the [Technologies and background reading](https://techfolios.github.io/techfoliodesigner/#technologies-and-background-reading) section of the Developer Guide. Review the materials on Electron, HTML/CSS, Semantic UI, React, Redux, Simple Git, and Code Mirror. (This will take several hours at a minimum).

## Sample Developer Tasks

Install TechFolio Designer from source, build, and run it using the instructions in the Developer Guide. Here are some simple tasks you can do to help become familiar with the code base:

### 1. Change background color of Splash Page

Change the background color of the splash page to light grey.

### 2. Add "last modified" timestamp to Splash page

Add a new row to the Splash page called "Last Modified" whose value is a nicely formatted timestamp (using Momentjs). Whenever something changes in the Splash page (i.e. a value changes in the table, or new text is printed to the Command Logs, the value of the timestamp should be updated to reflect that change.

### 3. Add menu item to Config menu.

Add a menu item called "Get Current Time" to the Config menu.  When this menu item is selected, a notification window is created with text indicating the current time. 

### 4. Add simple validation to Set GitHub Repo name

When specifying the TechFolio repo using "Set GIthub Repo name" check to make sure the provided text string ends with ".github.io".  If it doesn't, signal an error and do not set the repo name.

### 5. Allow four networks in the Simple Bio Editor

The current Simple Bio Editor only allows three Networks. Enhance it to allow four networks.

### 6. Perform simple validation on Project and Essay files.

When the user attempts to save a Project or Essay, check to see that the "date:" field is in YYYY-MM-DD format.  If not, save the file but also provide a notification that the date field was not valid.

## Write a TechFolio essay discussing your experience 

After you have finished this exercise, create and publish an essay (using TechFolio Designer, of course) that discusses your experience with this onboarding task. Provide screen shots that illustrate the results of implementing each of the 6 enhancements.  For each enhancement, explain what files needed to be changed, what you learned about the system, and what problems you ran into and how you solved them. 

When you are finished with the essay, post the URL as a comment to this issue and also post the URL in the onboarding channel of the Techfolios Slack workspace.

**Comment by blaine-wataru** [comment]
https://blaine-wataru.github.io/essays/techfoliodesignerexperience1.html

**Comment by saehyuns** [comment]
https://saehyuns.github.io/essays/TechFoliosOnboarding2.html

**Comment by adi-kumar** [comment]
https://adi-kumar.github.io/essays/first-techfolio-issues.html

**Comment by kiankoba** [comment]
https://kiankoba.github.io/essays/onboardingagain.html

**Comment by klauritz** [comment]
https://klauritz.github.io/essays/TechfolioDesignerOnboarding2.html

**Comment by rcammack** [comment]
https://rcammack.github.io/essays/techFolioDesigner2.html
