### ISSUE TITLE
Log push failures

### ISSUE THREAD

**Issue by philipmjohnson** [techfolios/techfoliodesigner#24]
Do work for this task in a branch called issue-24.

Currently, the system silently fails when there is a problem pushing the local repo to GitHub.

Add the catch clause to the runPushThenStatus so that an error is printed when there is a problem.

**Comment by zhime** [comment]
! [rejected]        master -> master (fetch first)
pulling or fetching and merging the master branch should resolve it. Which is why it pushes correctly when using techfolio designer built from the updated master branch, but had the error when I used the techfolio designer installed a week ago.

**Comment by philipmjohnson** [comment]
Hi Chris,

Can you update the catch clause to check for this kind of message and then, in addition to sending it to the Command Logs window, send an additional message that says something like, "To fix this problem, please update your local repo by invoking the command Config > Advanced > Pull changes from GitHub repo. Then try committing your changes again."

**Comment by zhime** [comment]
Added the additional message. 
Meant to say that the techfolio needs to be pulled, not techfolio designer. Yesterday, it didn't work in the older techfolio designer because it was using the older techfolio repo (that needed to be pulled)

**Comment by philipmjohnson** [comment]
The current solution isn't quite perfect, because the "solution" message is added to the console regardless of what caused the push failure. It's possible the push could fail for other reasons than not having an up to date local repo.  But we can leave it this way for now.
