### ISSUE TITLE
Improve Markdown Preview window resizing behavior

### ISSUE THREAD

**Issue by philipmjohnson** [techfolios/techfoliodesigner#38]
Please do work for this issue in a branch named issue-38.

Entering markdown preview mode resizes the window in a janky manner. The window tends to get lots wider, which is not what users usually expect.

Here's a proposal. Instead of widening the current window, check to see that it's a minimal width, and then split the window in two without changing its width.  If the window is not minimally wide, then pop up a notification that the user should manually resize the window before attempting to enter window preview mode.

**Comment by AliciaLeong** [comment]
Edge case where user tries to preview an empty file is fixed and will now have a pop up saying no preview available. However, the user will have to toggle preview mode off and then on again in order to use preview mode again.
