### ISSUE TITLE
Can't Authorize in Pop-Up Browser

### ISSUE THREAD

**Issue by walter-grace** [techfolios/techfoliodesigner#51]
Can't seem to authorize, I have my email verified so it isn't that. Any tips?  
![Screen Shot 2019-09-12 at 4 34 53 PM](https://user-images.githubusercontent.com/31444892/64827967-701aa980-d57b-11e9-8535-61f5d47a7ac6.png)

**Comment by ita07** [comment]
Same error here, wont let me authorize it. Also im getting the message on the top even tho all browsers are up to date.

**Comment by yahyaqr** [comment]
I solve the problem by copying request url link in developer tools and paste it to chrome browser, it became clickable. But another problem occur 
![image](https://user-images.githubusercontent.com/41809239/158003080-159ca521-867e-4f60-9e5c-206fce0e93de.png)

**Comment by philipmjohnson** [comment]
Hi, I'm sorry, but this system is not currently under active development. The best approach until we get back to this system is to edit your techfolio source files manually.
